# Generated by Django 5.0.4 on 2024-05-02 19:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactForm",
            fields=[
                (
                    "contact_form_uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("customer_email", models.EmailField(max_length=254)),
                ("customer_name", models.CharField(max_length=64)),
                ("message", models.TextField()),
            ],
        ),
    ]
